accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register', views.registration, name='register'),
    path('logout', views.logout_user, name='logout'),
    path('login', views.login_user, name='login'),
     path('update', views.update_acount, name='update'),


    
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.view_posts, name='view_posts'),
    path('<int:post_id>/', views.post_detail, name='post_detail'),
    # path('<int:post_id>/share/', views.post_share, name='post_share')
]

events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('', views.list_events, name='list_events'),

    
]

introdesign/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from service import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact_us, name='contact_us'),
    path('events/', include('events.urls')),
    path('accounts/', include('allauth.urls')),
    path('plans/', include('plans.urls'), name='plans'),
    path('blog/', include('blog.urls'), name='blog:post_detail'),
    path('accounts/', include('accounts.urls'), name='accounts'),

     # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
    path('tinymce/', include('tinymce.urls')),

    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plans/urls.py
from django.urls import path

from . import views


app_name = 'plans'

urlpatterns = [
    path('', views.plan_list, name='plan_list'),
    # path('<int:plan_id>/', views.plan_detail, name='plan_detail'),
    path('<int:plan_id>/<str:plan_title>/<int:plan_price>/', views.plan_detail, name='plan_detail'),

    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.


class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("User must have an email address")
        if not username:
            raise ValueError("User must have a username")

        user = self.model(
            email=self.normalize_email(email),
            username =username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    ia_superuser = models.BooleanField(default=False)
    first_name = models.CharField(verbose_name='name', max_length=120)
    last_name = models.CharField(verbose_name='last_name', max_length=120)
    phone_number = models.CharField(verbose_name='phone_number', max_length=11)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from . models import Account

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'max_length':60, 
        'help_text':'Required. Add a valid email address'
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'max_length':120, 
        'help_text':'Please provide your first name name'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'max_length':123, 
        'help_text':'please provide your last name'
    }))
    password1 = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
    }))
    password2 = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
    }))
    phone_number = forms.RegexField(regex=r'^[0]\d{10}$', widget=forms.TextInput(attrs={
        'class':'form-control',
        'max_length':11, 
        'help_text':'Please provide your phone number'
    }))

    class Meta:
        model = Account
        fields = ("email", "username", "password1", "password2", "first_name", "last_name", "phone_number")

    
    




class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class':'form-control',
        'label':'Password',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class':'form-control',
        'label':'Email'
    }))

    class Meta:
        model = Account
        fields = ("email", "password")

    
    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid Login Details")


class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('email', 'phone_number', 'first_name', 'last_name', 'username')

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']

            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
            except:
                return email
            raise forms.ValidationError('Email "%s" is already in use.' % account)
            
    
    def clean_username(self):
        if self.is_valid():
            email = self.cleaned_data['username']

            try:
                username = Account.objects.exclude(pk=self.instance.pk).get(username=username)
            except:
                return username
            raise forms.ValidationError('Username "%s" is already in use.' % account.username)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import RegistrationForm, LoginForm, AccountUpdateForm

# Create your views here.

def registration(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('index')
        else:
            context['registration_form'] = form
    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'accounts/register.html', context)




def logout_user(request):
    logout(request)
    return redirect('index')


def login_user(request):
    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect("index")

    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect('index')
    
    else:
        form = LoginForm()
    context['login_form'] = form
    return render(request, 'accounts/login.html', context)


def update_acount(request):
    if not request.user.is_authenticated:
        return redirect("index")
    
    context = {}

    if request.POST:
        form = AccountUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()

    form = AccountUpdateForm(
        initial={
            "email":request.user.email,
            "username":request.user.username,
            "first_name": request.user.first_name,
            "last_name": request.user.last_name,
            "phone_number": request.user.phone_number
        }
    )

    context['update_form'] = form
    return render(request, 'accounts/update.html', context)

templates/accounts/login.html
{% load static %}
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>TheVillage</title>
<meta name="description" content="">
<meta name="author" content="">

<!-- Favicons
    ================================================== -->


<!-- Bootstrap -->
<link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">

<!-- Stylesheet
    ================================================== -->
    <!-- Libraries -->
    <link rel="stylesheet" href="{% static 'css/plan.css' %}">
    <link rel="stylesheet" href="{% static 'lib/animate/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/owlcarousel/assets/owl.carousel.css' %}">
    <!-- Libraries -->
<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/nivo-lightbox/nivo-lightbox.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/nivo-lightbox/default.css' %}">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">

</head>
<body>
    <nav id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container"> 
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand page-scroll" href="{% url 'index' %}"><img id="brand" src="{% static 'img/vill.jfif' %}" alt="logo" /></a> </div>
          
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'about' %}" class="page-scroll">About</a></li>
              <li><a href="{% url 'plans:plan_list' %}" class="page-scroll">Plans</a></li>
              <li><a href="{% url 'contact_us'%}" class="page-scroll">Contact</a></li>
              <li><a href="{% url 'events:list_events'%}" class="page-scroll">Events</a></li>
              <li><a href="{% url 'blog:view_posts'%}" class="page-scroll">Blog</a></li>
              {% if request.user.is_authenticated %}
              <li><a href="#" class="page-scroll">Hi, {{request.user.username}}</a></li>
              <li><a href="{% url 'accounts:logout' %}" class="page-scroll">Log out</a></li>
              <li><a href="{% url 'accounts:update' %}" class="page-scroll">Update</a></li>
              {% else %}
              <li><a href="{% url 'accounts:login' %}" class="page-scroll">Log in</a></li>
              <li><a href="{% url 'accounts:register' %}" class="page-scroll">Sign up</a></li>
              {% endif %}
            </ul>
          </div>
          <!-- /.navbar-collapse --> 
        </div>
      </nav>
    <div class="container">
        <div style="margin-top: 50px;">
            <div class="row">
                <div class="section-title text-center center">
                    <h3>Welcome<h3>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div  id="form-container" style="margin-bottom: 80px;" >
                    <h4>Log In</h4>
                    <div class="form-group">
                        <form method="POST">
                            {% csrf_token c%}
                            {% for field in login_form %}
                                <p>  
                                    <span>{{field.label_tag }}</span>
                                    {{field}}
                                    {% if field.help_text %}
                                        <small style="color: gray;">{{field.help_text}}</small>
                                    {% endif %}
                                    
                                </p>
                            {% endfor %}
                            {% for field in login_form %}
                                {% for error in field.errors %}
                                    <small style="color: red;">{{error}}</small>
                                {% endfor %}
                            {% if login_form.non_field_errors %}
                                <div style="color: red;">
                                    {{login_form.non_field_errors}}
                                </div>
                            {% endif %}
                            {% endfor %}
                            
                            <button type="submit" style="padding: 10px; background-color: #18d26e;color: #fff; border-radius: 5px;">Login</button>
                        </form>
                        <div class="d-flex flex-column">
                            <a class="m-auto" href="{% url 'password_reset' %}">Reset password</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="footer">
        <div class="container text-center">
          <div class="social">
            <ul>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="www.instagram.com/villagedotng"><i class="fa fa-instagram"></i></a></li>
              <li><a href="www.linkedin.com/in/thevillage"><i class="fa fa-linkedin-square"></i></a></li>
              <li><a href="#"><i class="fa fa-youtube"></i></a></li>
            </ul>
          </div>
          <div style="color: #fff;">371, Borno way, Spencer Street, Alagomeji-Yaba, Lagos</div>
          <div>
            <p style="color: #fff;">&copy; 2020 the Village</p>
          </div>
        </div>
      </div>
    
    <script type="text/javascript" src="{% static 'js/jquery.1.11.1.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/SmoothScroll.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/nivo-lightbox.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/jquery.isotope.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/jqBootstrapValidation.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/contact_me.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    
    <script src="{% static 'lib/js/main.js' %}"></script>
    <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/superfish/hoverIntent.js' %}"></script>
    <script src="{% static 'lib/superfish/superfish.min.js' %}"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
    <script src="{% static 'lib/touchSwipe/jquery.touchSwipe.min.js' %}"></script>
    
    
</body>

templates/accounts/register.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TheVillage</title>
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Favicons
        ================================================== -->
    
    
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    
    <!-- Stylesheet
        ================================================== -->
        <!-- Libraries -->
        <link rel="stylesheet" href="{% static 'css/plan.css' %}">
        <link rel="stylesheet" href="{% static 'lib/animate/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'lib/ionicons/css/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'lib/owlcarousel/assets/owl.carousel.css' %}">
        <!-- Libraries -->
    <link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nivo-lightbox/nivo-lightbox.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nivo-lightbox/default.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    
</head>
<body>
    <nav id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container"> 
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand page-scroll" href="{% url 'index' %}"><img id="brand" src="{% static 'img/vill.jfif' %}" alt="logo" /></a> </div>
          
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'about' %}" class="page-scroll">About</a></li>
              <li><a href="{% url 'plans:plan_list' %}" class="page-scroll">Plans</a></li>
              <li><a href="{% url 'contact_us'%}" class="page-scroll">Contact</a></li>
              <li><a href="{% url 'events:list_events'%}" class="page-scroll">Events</a></li>
              <li><a href="{% url 'blog:view_posts'%}" class="page-scroll">Blog</a></li>
              {% if request.user.is_authenticated %}
              <li><a href="#" class="page-scroll">Hi, {{request.user.username}}</a></li>
              <li><a href="{% url 'accounts:logout' %}" class="page-scroll">Log out</a></li>
              <li><a href="{% url 'accounts:update' %}" class="page-scroll">Update</a></li>
              {% else %}
              <li><a href="{% url 'accounts:login' %}" class="page-scroll">Log in</a></li>
              <li><a href="{% url 'accounts:register' %}" class="page-scroll">Sign up</a></li>
              {% endif %}
            </ul>
          </div>
          <!-- /.navbar-collapse --> 
        </div>
      </nav>
    <div class="container">
       <div style="margin-top:40px;">
        <div class="row">
            <div class="section-title text-center center">    
                <h2>Create Account with Us</h2>
                <hr>
            </div>
        </div>
            <div class="row">
               <div id="form-container" style="margin-bottom: 80px;" >
                <h4>Sign Up</h4>
                <div class="form-group">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in registration_form %}
                            <p>
                                {{field.label_tag }}
                                {{field}}
                                {% if field.help_text %}
                                    <small style="color: gray;">{{field.help_text}}</small>
                                {% endif %}
                                {% for error in fields.errors %}
                                <small style="color: red;">{{error}}</small>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <button type="submit" style="padding: 10px; background-color: #18d26e;color: #fff; border-radius: 5px; ">Create Account</button>
                    </form>
                </div>
               </div>
            </div>
       </div>
    </div>

    <div id="footer">
        <div class="container text-center">
          <div class="social">
            <ul>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="www.instagram.com/villagedotng"><i class="fa fa-instagram"></i></a></li>
              <li><a href="www.linkedin.com/in/thevillage"><i class="fa fa-linkedin-square"></i></a></li>
              <li><a href="#"><i class="fa fa-youtube"></i></a></li>
            </ul>
          </div>
          <div style="color: #fff;" >371, Borno way, Spencer Street, Alagomeji-Yaba, Lagos</div>
          <div>
            <p style="color: #fff;">&copy; 2020 the Village</p>
          </div>
        </div>
      </div>
    
    <script type="text/javascript" src="{% static 'js/jquery.1.11.1.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/SmoothScroll.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/nivo-lightbox.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/jquery.isotope.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/jqBootstrapValidation.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/contact_me.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    
    <script src="{% static 'lib/js/main.js' %}"></script>
    <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/superfish/hoverIntent.js' %}"></script>
    <script src="{% static 'lib/superfish/superfish.min.js' %}"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
    <script src="{% static 'lib/touchSwipe/jquery.touchSwipe.min.js' %}"></script>
    
</body>